name: intro_app
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  retrofit: '^4.0.3'
  dio: ^5.4.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  popover: ^0.2.9
  json_annotation: ^4.8.1
  mediaquery_sizer: ^1.1.0
  
  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit_generator: '^8.0.6'
  build_runner: '^2.4.8' 
  json_serializable: '6.7.1' 

flutter:
  uses-material-design: true
  assets: 
    - .env