name: intro_app
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ^3.1.1


dependencies:
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  retrofit: '^4.1.0'
  dio: ^5.4.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  popover: ^0.2.9
  json_annotation: ^4.8.1
  mediaquery_sizer: ^1.1.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.2
  
  
  english_words: ^4.0.0
  provider: ^6.0.0
  like_button: ^2.0.5
  path: ^1.8.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  icons_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit_generator: '^8.1.0'
  build_runner: '^2.4.8' 
  json_serializable: '6.7.1' 

flutter:
  uses-material-design: true
  assets: 
    - .env